from .LTX2EasyPromptQwen import NODE_CLASS_MAPPINGS as QWEN_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWEN_DISPLAY_NAME_MAPPINGS
from .LTX2VisionEasyPromptLD import NODE_CLASS_MAPPINGS as VISION_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VISION_DISPLAY_NAME_MAPPINGS

# Optional — loads if present, skips silently if not.
try:
    from .LTX2EasyPromptLD import NODE_CLASS_MAPPINGS as LD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LD_DISPLAY_MAPPINGS
except ImportError:
    LD_MAPPINGS = {}
    LD_DISPLAY_MAPPINGS = {}

NODE_CLASS_MAPPINGS = {**LD_MAPPINGS, **QWEN_MAPPINGS, **VISION_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**LD_DISPLAY_MAPPINGS, **QWEN_DISPLAY_NAME_MAPPINGS, **VISION_DISPLAY_NAME_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
